-   id: auto-optional
    name: auto-optional
    description: Adds the Optional type-hint to arguments where the default value is None
    entry: auto-optional
    language: python
    types: [python]
